---
# Source: ks-core-outside-cluster/templates/kubesphere-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubesphere-config
data:
  kubesphere.yaml: |
    authentication:
      authenticateRateLimiterMaxTries: 10
      authenticateRateLimiterDuration: 10m0s
      loginHistoryRetentionPeriod: 168h
      maximumClockSkew: 10s
      multipleLogin: true
      kubectlImage: kubesphere/kubectl:latest
      jwtSecret: "xK064ToMKXP8kZHWGUfNKiamn7hKVWB6"
    monitoring:
      endpoint: http://prometheus-operated.kubesphere-monitoring-system.svc:9090
