---
# Source: ks-core/templates/ks-console-config.yml
apiVersion: v1
data:
  local_config.yaml: |
    server:
      http:
        hostname: localhost
        port: 8000
        static:
          production:
            /public: server/public
            /assets: dist/assets
            /dist: dist
      redis:
        port: 6379
        host: redis.kubesphere-system.svc
      redisTimeout: 5000
      sessionTimeout: 7200000
    client:
      version:
        kubesphere: v3.1.0
        kubernetes: v1.19.4
        openpitrix: v3.1.0
      enableKubeConfig: true
kind: ConfigMap
metadata:
  name: ks-console-config
  namespace: kubesphere-system
